---
- name: Reload Environment for Java
  command: source /etc/environment

- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"